accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/', views.profile, name="profile"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_ajax.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud_ajax/urls.py
from django.urls import path
from . import views
app_name = 'crud_ajax'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts-data/<int:num_posts>', views.load_post_data_view, name='posts_data'),
    path('like-unlike/', views.likeUnlikePostView, name='like_unlike'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/data/', views.load_post_detail_data_view, name='post_detail_data'),
    path('<slug:slug>/update/', views.post_detail_udpate, name='post_update'),
    path('<slug:slug>/delete/', views.post_detail_delete, name='post_delete'),
]

templates/base/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'crud_ajax/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
    <div class="header-content">

      <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="next" type="hidden" value="/" />
  
          <select class="selectpicker" name="language" style="width: auto;" onchange="this.form.submit()">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
  
                <option
                  value="{{ language.code }}"
                  {% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}
                  data-content='<img src="/static/images/flags/{{ language.code }}.gif"></span>
                  <span style="display:inline-block; width:100px; padding-left: 10px; text-shadow:none">
                    {{ language.name_local }}
                    <!-- span style="color:#999;">&nbsp;[{{ language.code }}]</span -->
                  </span>'>
                  {{ language.code }}
                </option>
  
            {% endfor %}
          </select>
      </form>
  
  </div>
  </head>
  <body>
    {% include 'base/navbar.html' %}
    {% include 'base/messages.html' %}
 
    {% block body %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="{% static 'crud_ajax/js/function.js' %}"></script>
    {% block script %} {% endblock %}
  </body>
</html>

templates/base/messages.html
<div id="alert-box">

</div>
{% if messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% for message in messages %}
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {% endfor %}
  </div>
{% endif %}

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
    <div class="container">
      <a class="navbar-brand" href="{% url 'crud_ajax:index' %}">Django and Ajax</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' %}">{{ request.user.username|title }}'s Profile</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <form role="search">
          <input class="form-control" placeholder="Search" aria-label="Search" type="search">
        </form>
      </div>
    </div>
  </nav>